# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/KostyOvo/android_kernel_oneplus_sm8250
          kernel-dir: msm-4.19
          kernel-branch: lineage-23.0
          config: cat_defconfig
          arch: arm64
          aosp-gcc: false
          aosp-clang: true
          android-version: 16
          aosp-clang-version: r487747c
          disable-lto: true
          anykernel3: true
